### ISSUE TITLE
Sunburst graph makes key label of Gauge graph disappear

### ISSUE THREAD

**Issue by RaulEstrada** [proteus-h2020/proteic#89] opened 2016-10-23 17:16 UTC
I have two graphs in the same page: a Gauge graph and a Sunburst graph, in two different divs. When I first access the page, both of them are displayed correctly. However, when I hover over an element of the Sunburst graph, the key of the Gauge one disappears and it's not visible until I refresh the page.

The code I use to create the Gauge graph is the following:

`var gauge = new proteic.Gauge([{x: notaMedia}], {
     minLevel: 0,
     maxLevel: 10,
     ticks: 1,
     selector: '#estudiantesMedias',
     label: 'Nota media'
   });
  gauge.draw();`

The code I use to create the Sunburst graph is the following:

`var sunburst = new proteic.Sunburst(dataGrafica, {
      selector: '#estudiantesNotasAlfabeticas'
  });
  sunburst.draw();`

The Gauge graph when I first access the page:
![before](https://cloud.githubusercontent.com/assets/6322230/19628001/8f2f43e6-9954-11e6-8441-ac5be1871467.png)

The Gauge graph after I hover over the Sunburst one:
![after](https://cloud.githubusercontent.com/assets/6322230/19628003/9412ccb6-9954-11e6-9f06-f9cae89be1e5.png)

**Comment by 0xNacho** [comment] 2016-10-23 20:33
Hi @RaulEstrada .
Thanks for reporting this issue! However, I cannot locally reproduce this issue. Could you set up a jsFiddle with the JS and the HTML code?

Thanks in advance.

**Comment by 0xNacho** [comment] 2016-10-23 20:43
I've located the offending lines: https://github.com/proteus-h2020/proteic/blob/development/src/svg/components/sunburstDisk.js#L44-L65

The issue seems to be a no refactored piece of code. We are fixing it ASAP.

Many thanks again!

**Comment by jorgeyp** [comment] 2016-10-24 07:42
This should be fixed in 177c4251edf91ab0d16aa63e459bb7cd77680ec6, thanks @RaulEstrada!

**Comment by 0xNacho** [comment] 2016-10-24 10:28
Could you confirm that the issue has been fixed? @RaulEstrada

**Comment by RaulEstrada** [comment] 2016-10-24 13:42
Yes, the issue has been fixed. It doesn't happen anymore.

**Closed** 2016-10-24 13:56 UTC
Labels: bug
